# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53c956ed309df64109767ebe3c9da284c07259bd5b78e90d82c75c14e1a6aff7f18b2dbc696675b63c474beb2997232100640d885e5c6024fb48c0c3014ebae8

test:
  secret_key_base: 155e5b9463452267f7fef22289a6b7d28f47fad320788d43e21393d127ab0b8826b432d7717332c96b6f57142e0fe598c7edbe5e9ecec6031c66d3372b0e15c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
